### ISSUE TITLE
On start view : Could not set the 'set-cookie' HTTP header

### ISSUE THREAD

**Issue by mrtdeh** [bennyboer/bbb_app#107]
I tried to enter to meeting but:

![Screenshot from 2020-12-01 21-25-12](https://user-images.githubusercontent.com/7369151/100780484-03f5c100-341f-11eb-961c-17816b8bc8fb.png)

what the username?
what the meeting url?

**Comment by bennyboer** [comment]
Hi there! We use a current BigBlueButton installation with Greenlight installed. Then the Meeting URL is the same which you can share to invite other people.

**Comment by mrtdeh** [comment]
This is what i send :

https://****/bigbluebutton/api/join?fullName=mrtdeh&meetingID=random-9485175&password=ap&redirect=true&checksum=0eadfd7456a0ef61417ece1aac9fa058f60fda8d

So what else to use...?

**Comment by bennyboer** [comment]
https://HOST/b/ede-6t9-7qf

or alike

**Comment by mrtdeh** [comment]
what was that??????
i use api mate for generate there links but ...
but where can I get this link you sent?

**Comment by bennyboer** [comment]
We only use the web interface Greenlight for BigBlueButton, so we didn't yet check other ways of connecting. Anyways this project is like 6 weeks old

**Comment by mrtdeh** [comment]
Thanks for help

**Comment by bennyboer** [comment]
Hi there, we will support the direct join URL (without Greenlight) when #119 is done (Should be done by the end of the week hopefully)!

**Comment by irfanakram825** [comment]
Hi there, I'm also facing the problem. How do you guys manage to solve this issue? 
I'm using api join meeting url like `https://bbblive.mydomain.com/html5client/join?sessionToken=k1j234r5tygf` in meeting url input field and on joining getting same error.
