### ISSUE TITLE
Waiting rooms are still buggy

### ISSUE THREAD

**Issue by jo-code** [bennyboer/bbb_app#116]
Sometimes when the moderator approved you to joing the meeting, you are instantly kicked from the meeting: 
![image](https://user-images.githubusercontent.com/32556193/101244813-ca67d300-3708-11eb-88b1-d406eea716bd.png)

**Comment by bennyboer** [comment]
Happens not only for waiting rooms, but generally

**Comment by bennyboer** [comment]
Haven't seen this behavior for a long time. So I am going to close it for now.
