### ISSUE TITLE
Send message via BBB WebRTC

### ISSUE THREAD

**Issue by VietThang-Antoree** [bennyboer/bbb_app#137]
Hi, I'm having trouble finding the list of messages you can send to the BBB Web RTC. Could you please provide the documentation of the message's formats of BBB to send, message to draw a line for example?

Thanks in advance. I appreciate your help

**Comment by Gleydar** [comment]
Hi, we described some of the messages in our wiki https://github.com/bennyboer/bbb_app/wiki. However, the list is not yet complete and will be expanded.

**Comment by bennyboer** [comment]
There is not much documentation from the BBB side regarding this topic. My best advice would be to fire up a conference and use the Chrome DevTools to check the websocket traffic in the network tab of the official BBB web app. Then you will see what message format is sent over when you draw a line for example.
