### ISSUE TITLE
Unable to view IOS participant camera

### ISSUE THREAD

**Issue by labomatik** [bennyboer/bbb_app#140]
Hello, 

On IOS (and macOS M1) we are unable to view the participant camera, the system is indefinitely loading.
Do you have any idea what to check?
<img width="1198" alt="Capture d’écran 2021-02-01 à 17 54 35" src="https://user-images.githubusercontent.com/179987/106491213-eb556600-64b6-11eb-8860-c3bb6eafa11b.png">

**Comment by bennyboer** [comment]
@lukaskirner Can you check if we have the same problem on our test system?

**Comment by lukaskirner** [comment]
I checked it. On my devices (iPhone 12, and iPad Pro 2018) I have no problem to view the other participants.  @labomatik can you please share more information about your setup with us? Like your iPhone, iOS Version and the BBB Server Version.

Also I'm not sure if the framework we are using works great with the new Apple M1 Chips.

**Comment by labomatik** [comment]
It's an iphone 11 Pro with IOS 14.3
bbb app is a bit behind but is working correctly: bbb-apps 2.2.0-42

in the javascript of the moderator (the one that tries to display the IOS camera) i can see this:

`[19:54:07:0704] ERROR: clientLogger: Camera VIEWER has not succeeded in 15000 for w_dzpqn6bmgk4o. Reconnecting. https://bbb.server.biz/html5client/cbdf17782969bc4b3fe30773a814528cae4e716d.js?meteor_js_resource=true:121:350428
cbdf17782969bc4b3fe30773a814528cae4e716d.js?meteor_js_resource=true:9 [19:54:07:0705]  INFO: clientLogger: Sending stop request to SFU. Camera: w_dzpqn6bmgk4o, role viewer and flag restarting true A.stopWebRTCPeer (https://bbb.server.biz/html5client/cbdf17782969bc4b3fe30773a814528cae4e716d.js?meteor_js_resource=true:121:347461)
cbdf17782969bc4b3fe30773a814528cae4e716d.js?meteor_js_resource=true:9 [19:54:07:0705]  WARN: clientLogger: Peer w_dzpqn6bmgk4o was already disposed (glare), ignore it. A.destroyWebRTCPeer (https://bbb.server.biz/html5client/cbdf17782969bc4b3fe30773a814528cae4e716d.js?meteor_js_resource=true:121:348128)
cbdf17782969bc4b3fe30773a814528cae4e716d.js?meteor_js_resource=true:9 [19:54:07:0750]  INFO: clientLogger: Camera offer generated. Sending start request to SFU for w_dzpqn6bmgk4o WebRtcPeerRecvonly.<anonymous> (https://bbb.server.biz/html5client/cbdf17782969bc4b3fe30773a814528cae4e716d.js?meteor_js_resource=true:121:349611)
cbdf17782969bc4b3fe30773a814528cae4e716d.js?meteor_js_resource=true:9 [19:54:07:0752]  INFO: clientLogger: Camera has a new reconnect timer of 30000 ms for w_dzpqn6bmgk4o A.setReconnectionTimeout (https://bbb.server.biz/html5client/cbdf17782969bc4b3fe30773a814528cae4e716d.js?meteor_js_resource=true:121:351238)
cbdf17782969bc4b3fe30773a814528cae4e716d.js?meteor_js_resource=true:9 [19:54:07:0753] DEBUG: clientLogger: video-provider client-side candidate queued for w_dzpqn6bmgk4o WebRtcPeerRecvonly.<anonymous> (https://bbb.server.biz/html5client/cbdf17782969bc4b3fe30773a814528cae4e716d.js?meteor_js_resource=true:121:351645)
cbdf17782969bc4b3fe30773a814528cae4e716d.js?meteor_js_resource=true:9 [19:54:07:0781] ERROR: clientLogger: SFU returned error for camera w_dzpqn6bmgk4o. Code: 2201, reason: MEDIA_NOT_FOUND A.handleSFUError (https://bbb.server.biz/html5client/cbdf17782969bc4b3fe30773a814528cae4e716d.js?meteor_js_resource=true:121:357707)`

**Comment by labomatik** [comment]
Just did a test on https://demo1.bigbluebutton.org/ and there all is ok, i'll try to upgrade our bbb server to give it a try.

Christophe

**Comment by lukaskirner** [comment]
@labomatik Your BBB server [https://bbb.server.biz](https://bbb.server.biz) has `SSL_ERROR_BAD_CERT_DOMAIN` maybe this could be the problem

**Comment by labomatik** [comment]
i've replaced to a dummy url for security but i can send you some links in private if needed

**Comment by labomatik** [comment]
Tested on a fresh BBB server and the participant camera can be displayed, so i guess i'll need to update the prod server to 2.2.31.

**Comment by bennyboer** [comment]
Thank you for the investigation!
