### ISSUE TITLE
Presentation won't load if the user starts the session with his join

### ISSUE THREAD

**Issue by lukaskirner** [bennyboer/bbb_app#141]
How to reproduce:
1. Join session which was not opened before
2. Infinite loading spinner for presentation

**Comment by lukaskirner** [comment]
What I have noticed so far:

Normal (session is already open):
- only "added" messages come in for presentation

Bug (session is not open):
- "added" message doesn't include enough information for presentation object
- "changed" messages come later including information for the presentation object (But at setting this information nullpointer occures)
- `Presentation presentation = _presentationsByID[id];` --> is null

**Comment by bennyboer** [comment]
Thanks for the investigation!

**Comment by lukaskirner** [comment]
Still not loading on the newest master

**Comment by lukaskirner** [comment]
To test it you need to close the meeting manually over the web client. That means if you start a new attempt you need to log in with the web client before and close the meeting there. Just leaving the meeting with the app does not completely close the BBB session.
