### ISSUE TITLE
Ability to hide fullscreen items (video and presentation)

### ISSUE THREAD

**Issue by labomatik** [bennyboer/bbb_app#147]
Currently when we click the fullscreen button on a video or the presentation it is difficult to go back to the "normal" layout.
The only possibility on IOS is to swipe from left to right.
I guess it's easier on Android with the back button.
There should be a possibility to add an icon on top of maximized items to minimize them.

**Comment by bennyboer** [comment]
You're right! Haven't thought about iOS when I was designing this.
