### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by bennyboer** [bennyboer/bbb_app#15]
Leave the meeting:

- [x] Tell open connections to close
- [x] Call logout when the app is closed
- [x] Implement leave button in the UI triggering the logout

**Comment by bennyboer** [comment]
@jo-code Can you take a look at this later? I pushed the code, the web client does receive a message (user changed) with attribute loggedOut: false. But when a web client is logging out, there is another user changed message (validated: false) and only after that the user is no more listed in the participants list in the web client. That second message is missing when logging out from the app and I cannot figure out why 😄

**Comment by bennyboer** [comment]
@jo-code Seems like the code in `bigbluebutton-html5/imports/api/users/server/publishers.js` should have been called, but it wasn't. Maybe we need the server logs from the IT Ops team to check the error, or we need to figure out how to cause the MeteorJS connection to close:
![grafik](https://user-images.githubusercontent.com/14014633/97781657-39dc2700-1b8d-11eb-9b8c-42e29ae3762d.png)

**Comment by jo-code** [comment]
Unfortunately I could not find anything that we do differently compared to the Web Client. We have to take a closer look again...
