### ISSUE TITLE
Audio connected twice after failed join attempt

### ISSUE THREAD

**Issue by bennyboer** [bennyboer/bbb_app#156]
From issue #131:

> I can confirm that with #155, the audio does connect on 2.2.31, BUT:
> 
> being a single client in the meeting, apparently the app connected 2 times, which made me hear myself (like echo test) in a single-participant room.

Adding to above: since it apparently connected 2 times, the mute button worked on only one of the connections, practically made it impossible to mute

I'll have to add that the first join attempt failed with the app jumping back to login page (apparently sip connected anyway!), and second attempt did actually join the room, opening a second concurrent sip connection.

This can also count as a security threat, having a room seemingly not joined, but sip is transmitting audio without user consent.

_Originally posted by @siavash79 in https://github.com/bennyboer/bbb_app/issues/131#issuecomment-774411535_

**Comment by bennyboer** [comment]
@siavash79 Is the behavior reproducable in your environment? Because I am having trouble experiencing the failed join attempt. I have added error logging in this case on branch `156-audio-connected-twice`. Can you try with that branch and send me the log?

**Comment by siavash79** [comment]
This is the logcat dump. I'm not sure if you added any logfile to the branch or not, so I just dump the logcat here.

[logcat.txt](https://github.com/bennyboer/bbb_app/files/5936830/logcat.txt)

Also, here's a screen capture. You can clearly hear the voice echo, even from the join page:

https://youtu.be/CTYGQpDVcKE (still uploading as of this post)

**Comment by bennyboer** [comment]
Thank you! It seems like the app thinks you've been kicked from the meeting. I will check what's wrong there!

**Comment by siavash79** [comment]
Plus: If it helps, this is the server-side recorder log:

[events.txt](https://github.com/bennyboer/bbb_app/files/5936840/events.txt)
