### ISSUE TITLE
Incompatible Android devices (motorola g8 power)

### ISSUE THREAD

**Issue by danfelbm** [bennyboer/bbb_app#164]
**Describe the bug**
I wonder why a device like a "moto g8 power" is not compatible with the app? What technical aspects would have to be fixed or taken into account for such device to become compatible?

**To Reproduce**
1. Basically go to the Play Store with a motorola device and see if it's compatible or not. The ones I've tested (below moto g8; I haven't tested other more high-tier brands)

**Expected behavior**
The app to be compatible. I haven't really been able to build my own apk to test if it works manually. I'd believe it should be compatible because the app in its current staten (in terms of features) should pretty much work like Jitsi App, which is indeed compatible with my device.

**Screenshots**
no screenshots.

**Smartphone (please complete the following information):**
 - Device: moto g8 power
 - OS: android 10

**BBB Server**
I don't remember exactly, but is not relevant to this issue.

**Additional context**
I wonder if this is totally expected or intended?
Another question I have is simply if there's any way I can donate for the development of this app? Unfortunately I wouldn't be able to contribute in terms of development, but I'd definitely donate and spread the word, because I think is a very much needed feature for BBB and it'd certainly take it to the next level. 
Thank you for your work on this!

**Comment by bennyboer** [comment]
Hi there!

In fact google play lists the moto g(8) power as supported. Can you try installing it without Google Play by downloading the APK from https://github.com/bennyboer/bbb_app/releases/download/v0.2.3%2B6/app-release.apk ?

**Comment by danfelbm** [comment]
It works. Quite strange. Could it be related to my location? Probably an issue with Play Store.

An issue I'm having is that I'm not sure what URL I'm supposed to use to enter a meeting. All possible URLs give me an error when trying to connect.

**Comment by bennyboer** [comment]
Maybe, I just released the app for germany at the moment as it's still early access.

We expect a greenlight URL, such as https://my-bbb-instance.com/b/mee-tin-g42

**Comment by danfelbm** [comment]
That might be it @bennyboer . I'm not using Greenlight but Moodle/WordPress APIs. So the URLs available for me are either inside a meeting or outside in a wp/moodle page.

**Comment by Gleydar** [comment]
In this case, we offer the redirect app, which you can deploy if you are the administrator of your website. https://github.com/bennyboer/bbb_app/blob/main/redirect/README.md

**Comment by bennyboer** [comment]
If you can get hold of the direct join link from moodle, you can use our redirect web app to join via the app: https://bennyboer.github.io/?target=DIRECT_JOIN_LINK

**Comment by bennyboer** [comment]
@Gleydar Ok well you were first

**Comment by bennyboer** [comment]
I will close this, if there is anything else, just go ahead and create another issue!
