### ISSUE TITLE
Cannot join meetings with a custom lobby website

### ISSUE THREAD

**Issue by iMonZ** [bennyboer/bbb_app#168]
**Describe the bug**
I cannot join the Meeting on websites with a custom lobby

**To Reproduce**

I used a free custom server from bbbserver.de and maybe because of the custom lobby the joining is not possible

**Additional context**
https://user-images.githubusercontent.com/11319871/107760717-84dc0d80-6d2a-11eb-8400-c8ac7f7188ac.MP4

**Comment by Gleydar** [comment]
Hi, yes, we do not support joining via this method, the app directly only accepts the default greenlight interface. 
If you have a direct join link, you can use https://bennyboer.github.io/?target=DIRECT_JOIN_LINK. However, due to the complex nature of the project we will not be able to support every web interface.

**Comment by iMonZ** [comment]
Thank you but
The website does not exists.

**Comment by bennyboer** [comment]
`bbb_app` was missing in the URI!

`https://bennyboer.github.io/bbb_app/?target=https://DIRECT_JOIN_LINK` is correct :smile:

**Comment by iMonZ** [comment]
> https://bennyboer.github.io/bbb_app/?target=https://DIRECT_JOIN_LINK

There is a google play link but whats with the IOS link?

**Comment by lukaskirner** [comment]
> There is a google play link but whats with the IOS link?

The given URL is just a static web page which will give the user the choice of opening the BBB session with the app or the classic web app. It also works both iOS and Android. The `target` query parameter specifies the session. This could be either a Greenlight URL or the API join URL (<host>/api/join ...)

**Comment by bennyboer** [comment]
I think @iMonZ means that the iOS link is missing. Created issue #169.

**Comment by iMonZ** [comment]
> I think @iMonZ means that the iOS link is missing. Created issue #169.

Thank you!
Is the source of this website available?

**Comment by bennyboer** [comment]
Sure: https://github.com/bennyboer/bbb_app/tree/main/redirect

**Comment by iMonZ** [comment]
> Sure: https://github.com/bennyboer/bbb_app/tree/main/redirect

Oh this Source was inside the source of this App that’s why I couldn’t found it ^^
But thanks

**Comment by edmundlaugasson** [comment]
Tried to use own instance of BBB and could not connect, neither public or private session. I have authentication via Nextcloud and not publicly. Although BBB itself  has default interface (lobby). There is also authentication sometimes needed as not all BBB sessions are not public.
