### ISSUE TITLE
Using as module (App-in-App)

### ISSUE THREAD

**Issue by hamedvbv** [bennyboer/bbb_app#170]
We have an app in our university and need to use the project as app-in-app. I converted the project to module and run the command:
`flutter build aar`

but get below issue:

The plugin "flutter_foreground_plugin" is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when Flutter is integrated into an
existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.
Running Gradle task 'assembleAarDebug'...                               
Running Gradle task 'assembleAarDebug'... Done                      8.5s

FAILURE: Build failed with an exception.

* Where:
Initialization script '/flutter/common/flutter/packages/flutter_tools/gradle/aar_init_script.gradle' line: 156

* What went wrong:
Failed to notify build listener.
> assert moduleProject != null
         |             |
         null          false

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

Is it possible to use the project as a module?

**Comment by bennyboer** [comment]
You should contact the maintainer of the plugin `flutter_foreground_plugin` about this.
