### ISSUE TITLE
RELEASE `v0.2.6` TESTING

### ISSUE THREAD

**Issue by bennyboer** [bennyboer/bbb_app#171]
General testing before releasing `v0.2.6`.

**Comment by bennyboer** [comment]
Found #172 (Not really release critical)

**Comment by bennyboer** [comment]
Found #173 should be fixed before releasing

**Comment by bennyboer** [comment]
Found #174 should be fixed before releasing

**Comment by bennyboer** [comment]
Found #175 which should be fixed before releasing

**Comment by bennyboer** [comment]
Found #176 that should be fixed before releasing

**Comment by bennyboer** [comment]
Testing done from my side

**Comment by lukaskirner** [comment]
Found #178 Missing indication about who is currently talking
