### ISSUE TITLE
Fix `dart_sip_ua` dependency (see comments)

### ISSUE THREAD

**Issue by freehussain** [bennyboer/bbb_app#191]
hello,

i try to build the app with flutter 1.22.6 but there is many errors comes , is there any build instruction ???

kind regards

**Comment by bennyboer** [comment]
Hi there! Can you post the errors?

**Comment by freehussain** [comment]
lib/src/connect/meeting/main_websocket/voice/call_manager.dart:83:32: Error: The setter 'transport_scheme' isn't defined for the class 'WebSocketSettings'.
 - 'WebSocketSettings' is from 'package:sip_ua/src/sip_ua_helper.dart' ('../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/sip_ua-0.3.5/lib/src/sip_ua_helper.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'transport_scheme'.
    settings.webSocketSettings.transport_scheme = transportScheme;
                               ^^^^^^^^^^^^^^^^

**Comment by bennyboer** [comment]
Just checked, but dart_sip_ua does have the field on the WebSocketSettings class. Can you check whether you have the right version like specified in pubspec.yaml (Git link) installed using pub get?

**Comment by freehussain** [comment]
this is my pubspec.yaml , i just removed the version because an error comes if i use it

name: bbb_app
description: BigBlueButton client app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.2.6+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  flutter_webrtc:
  shared_preferences:
  shared_preferences_macos:
  shared_preferences_web:
  http:
  html:
  day_night_switcher:
  provider:
  intl:
  sprintf:
  flutter_svg:
  crypto:
  sip_ua: ^0.3.5

  flutter_markdown:
  uni_links:
  flutter_foreground_plugin:
  logger: ^0.9.4
  bloc:
  flutter_bloc:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  vector_math: any


flutter:


  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/GitHub_Logo.png
    - assets/privacy_policy/de.md
    - assets/privacy_policy/en.md

  

flutter_icons:
  android: true
  image_path_android: "assets/icon/android/icon.png"
  ios: false
  image_path_ios: "assets/icon/ios/icon.png"

**Comment by bennyboer** [comment]
In the latest `pubspec.yaml` on the `main` branch (https://github.com/bennyboer/bbb_app/blob/main/pubspec.yaml) we use:

```
sip_ua:
  git: https://github.com/flutter-webrtc/dart-sip-ua.git
```

instead of:
```
sip_ua: ^0.3.5
```

since `sip_ua` 0.3.5 does not yet contain a fix we need to support BBB 2.2.31

**Comment by freehussain** [comment]
hello,

it comes with another error 

/Users/hussain/Documents/flutter/bin/flutter --no-color pub get
Running "flutter pub get" in bbb_app...                         



The current Dart SDK version is 2.10.5.

Because every version of sip_ua from git depends on crypto >=3.0.0-nullsafety.0 which requires SDK version >=2.12.0-0 <3.0.0, sip_ua from git is forbidden.
So, because bbb_app depends on sip_ua from git, version solving failed.
pub get failed (1; So, because bbb_app depends on sip_ua from git, version solving failed.)

**Comment by bennyboer** [comment]
Ah I see! Seems like they sneaked Dart nullsafety in there!

Try:

```
sip_ua:
  git:
    url: https://github.com/flutter-webrtc/dart-sip-ua.git
    ref: d05b5fd26ec7a2bee5127ed67fe1bcbf4d2a8748
```

It will take the latest commit we know is working of `dart_sip_ua`.

**Comment by freehussain** [comment]
hello,

thank you, it works now :)

**Comment by bennyboer** [comment]
No problem! Thank you for finding the issue. I will keep this open as a reminder to fix it once I have time again around July!
