### ISSUE TITLE
The argument type 'String' can't be assigned to the parameter type 'Uri'

### ISSUE THREAD

**Issue by MayankChopra12** [bennyboer/bbb_app#196]
Error -
Uri' is from 'dart:core'.
    http.Response response = await http.get(url);
FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035
 ------------------------------------------------------------------------

description - 
this same error is coming in many files -  (main_websocket.dart, start_view.dart, etc)

I am able to solve this error using Uri.parse(string argument) but after that more error is coming.
 --------------------------------------------------------------------------------------------

the error after resolving above error are as following - 
(A)--
error: FlutterForegroundPlugin() has private access in FlutterForegroundPlugin
    flutterEngine.getPlugins().add(new changjoopark.com.flutter_foreground_plugin.FlutterForegroundPlugin());

(B)--
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by bennyboer** [comment]
What Flutter version are you using? We're still at Flutter `1.22.6`

**Comment by MayankChopra12** [comment]
> What Flutter version are you using? We're still at Flutter `1.22.6`



> What Flutter version are you using? We're still at Flutter `1.22.6`

it is my mistake, I am using 2.2. 1, thanks for reply.

**Comment by MayankChopra12** [comment]
Thanks , it works now
