### ISSUE TITLE
Opening the app from Moodle

### ISSUE THREAD

**Issue by freehussain** [bennyboer/bbb_app#200]
hello,

we need to open the app from moodle when click join , is there any way for this?

**Comment by bennyboer** [comment]
@lukaskirner Can you provide a description of the way we did it?

**Comment by lukaskirner** [comment]
Sure! We actually just redirected one specific moodle URL to the app opener web page. The snippet below shows an NGINX configuration which will do this:

```
        ...
        location /mod/bigbluebuttonbn/ {
            proxy_pass  http://moodle:8080;
            
            proxy_hide_header Location;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            add_header Location "https://bennyboer.github.io/bbb_app/?target=$upstream_http_Location";
        }
        ...
```

**Comment by bennyboer** [comment]
@lukaskirner Thanks! 😄

**Comment by freehussain** [comment]
hello @lukaskirner 

i mean deeplink to open this app instead of browser if it is already installed

**Comment by bennyboer** [comment]
The redirect web app at https://bennyboer.github.io/bbb_app is basically doing that already but won't force the user to use the app if they do not have it installed.

If you really want to open the app (which will fail, if the user does not have the app installed), you can always just use the `bbb-app://` protocol instead of `https://` like 
bbb-app://my-bbb-instance.com/b/mee-tin-g42 (Greenlight example). This will also work for direct join links that are generated by the BBB Moodle plugin.

**Comment by freehussain** [comment]
no there little deffernce on the link

greenlight link bbb-app://my-bbb-instance.com/b/mee-tin-g42 

moodle link: https://url/bigbluebutton/api/join?fullName=name&join_via_html5=true&meetingID=meeting-id-unumber&password=PassW0rd&userID=gl-guest-ccf1336598395192e46aa860&checksum=a01cc2d26a1fee1b35f8b96c46185d82d3eaf6f3


in the code it was generated from function  "_postJoinForm", can we just fill it from deep link instead of post to green light

**Comment by bennyboer** [comment]
You can just use the link from the Moodle plugin with `bbb-app` instead of `https`. The app should be able to directly join the meeting

**Comment by freehussain** [comment]
i just tried to do like this 

 bbb-app://url/bigbluebutton/api/join?fullName=name&join_via_html5=true&meetingID=meeting-id-unumber&password=PassW0rd&userID=gl-guest-ccf1336598395192e46aa860&checksum=a01cc2d26a1fee1b35f8b96c46185d82d3eaf6f3


not working

**Comment by freehussain** [comment]
hello,

the above won't work, because the current code expect greenlight link

is there anyway to make the app get the link from url in this format 
bbb-app://url/bigbluebutton/api/join?fullName=name&join_via_html5=true&meetingID=meeting-id-unumber&password=PassW0rd&userID=gl-guest-ccf1336598395192e46aa860&checksum=a01cc2d26a1fee1b35f8b96c46185d82d3eaf6f3

@bennyboer
