### ISSUE TITLE
Can see camera video on web and Android APP but cannot on iOS APP, any suggestions?

### ISSUE THREAD

**Issue by MAYIGD** [bennyboer/bbb_app#211]
Can see camera video on web and Android APP but cannot on iOS APP, any suggestions?
Flutter 3.3.4
flutter_webrtc: ^0.9.11
Xcode 13.4

**Comment by blueromans** [comment]
Im facing same issue. Could you find a solution? @MAYIGD 
Flutter 3.3.10
flutter_webrtc: ^0.9.11
