### ISSUE TITLE
Sometimes current user is not displayed in participants list

### ISSUE THREAD

**Issue by jo-code** [bennyboer/bbb_app#34]

**Comment by jo-code** [comment]
Our app behaves correctly. Our participants list works correctly.

Problem is that login sometimes doesnt work properly, because when this issue happens, the user is also not visible in the web app. I also found out the bbb server then doesnt send all necessary information about the user on the websocket. E.g. intId is never sent by bbb server. Therefore the user is missing in our users list, which is why he cant be displayed in the participants list and also chat doesnt work.

**Comment by jo-code** [comment]
But this is not such a big problem at the moment. User simply has to leave meeting and login again as this issues occurrs not very often.

**Comment by bennyboer** [comment]
Issue does occur a lot to me lately, and I am not aware of it when for example typing in the chat.

Maybe we should wait when logging in for the answer of the server (There is a method updated message sent with the ID of our initial request). If the message is not received we can resend it.

**Comment by bennyboer** [comment]
Moved to CW 47 to reconsider fixing it

**Comment by jo-code** [comment]
still not working properly...
