### ISSUE TITLE
Surveys

### ISSUE THREAD

**Issue by jo-code** [bennyboer/bbb_app#37]

**Comment by bennyboer** [comment]
Probably should be done after #4 because the results are drawn on the presentation (I guess?)

**Comment by bennyboer** [comment]
Surveys are already rendered by the presentation widgets, so all that needs to be done is a dialog for choosing the poll option.

**Comment by bennyboer** [comment]
We can probably use the simple dialog: https://api.flutter.dev/flutter/material/SimpleDialog-class.html
