### ISSUE TITLE
make url field on start view more user friendly

### ISSUE THREAD

**Issue by jo-code** [bennyboer/bbb_app#43]
- Trim string (prevent blanks at start or end of string)
- auto add https:// if user forgets it

**Comment by bennyboer** [comment]
Why remove the www?

**Comment by jo-code** [comment]
> Why remove the www?

Because of reasons 😂 www is not working with our bbb-ext, but yes it might work with other servers...

**Comment by bennyboer** [comment]
> 
> 
> > Why remove the www?
> 
> Because of reasons 😂 www is not working with our bbb-ext, but yes it might work with other servers...

Yeah, but www may point to a valid server 😄 Our bbb-ext is doing it thus correctly, if they want it to work, they need to redirect on www. calls. So we should not fix this 😃
