### ISSUE TITLE
add BBB trademark disclaimer to app

### ISSUE THREAD

**Issue by jo-code** [bennyboer/bbb_app#58]
we should add the BBB trademakr disclaimer (which we already have in readme) to the app. Display it on start view and maybe on settings view.

https://bigbluebutton.org/trademark/

**Comment by bennyboer** [comment]
Following that guidelines we need to remove the name BigBlueButton from the start page. I guess it is ok to rename it to BBB App?

So maybe we could rename it to "BBB App" followed by a subtitle "Mobile client for BigBlueButton services". Sounds good @jo-code ?

**Comment by jo-code** [comment]
Yes that should be fine. 
And can you please change the repo description to include a "for" @bennyboer .

**Comment by jo-code** [comment]
And we should add the trademark symbol to the first prominent usages (readme, app):

_Do I have to put the trademark symbol every time I write the word “BigBlueButton”?

No, you only need to do so in the first prominent use._

@bennyboer

**Comment by bennyboer** [comment]
## TODO

- [x] Change repository description to include "for BigBlueButton"
- [ ] Include the following text on the start page of the app (This app uses BigBlueButton and is not endorsed or certified by BigBlueButton Inc. BigBlueButton and the BigBlueButton Logo are trademarks of BigBlueButton Inc.)
- [ ] Rename title in the start view from "BigBlueButton" to "BBB App"
