### ISSUE TITLE
App icon

### ISSUE THREAD

**Issue by bennyboer** [bennyboer/bbb_app#67]
We need to design an icon for the app.

**Comment by jo-code** [comment]
we need to updated the screenshot in readme

**Comment by jo-code** [comment]
and we need to check the svg. it has different font and different paddings compared to the png.

**Comment by bennyboer** [comment]
Maybe you dont have the proper font installed

**Comment by bennyboer** [comment]
# TODO

- [ ] Export SVG not to Inkscape SVG but to compressed SVG and show in README
- [ ] Change Screenshot in README of the start view
