### ISSUE TITLE
screenshare is still buggy

### ISSUE THREAD

**Issue by jo-code** [bennyboer/bbb_app#97]
It seems like the screenshare stream only starts after user klicked something in UI (e.g. open meeting info page and close again). I don't know why. Maybe someone has an idea or we take a look into this at the end if we have time left. But for now I think it's ok :)

**Comment by bennyboer** [comment]
Try calling `setState(() {})` when the stream should start maybe

**Comment by jo-code** [comment]
> Try calling `setState(() {})` when the stream should start maybe

tried. doesn't work :(

**Comment by bennyboer** [comment]
Tried multiple times, works perfectly fine on Android 11 for me. Maybe it's an Emulator problem. Thus closing! Good job @jo-code !
